Repository influxdata/chronograf, pull requests merged in 2018-04, with the labels that each got.

#3111 Fix saving of new TICKscripts
  CHANGELOG.md
  ui/src/kapacitor/components/TickscriptEditorControls.js
  ui/src/kapacitor/containers/TickscriptPage.js
Labels: bugfix

#3116 Improve Cell Renaming
  CHANGELOG.md
  ui/src/dashboards/components/VisualizationName.js
Labels: User Experience

#2832 Add measurements with pagination
  CHANGELOG.md
  chronograf.go
  influx/databases.go
  influx/permissions.go
  mocks/databases.go
  server/databases.go
  server/databases_test.go
  server/mux.go
  server/swagger.json
Labels: ready for review

#3157 Polish/Line+SingleStat Colors
  ui/src/dashboards/constants/cellEditor.js
  ui/src/shared/components/Dygraph.js
  ui/src/shared/components/SingleStat.js
  ui/src/shared/constants/colorOperations.js
  ui/src/shared/parsing/lastValues.js
Labels: polish

#3172 Fix Flickering Confirmation Tooltip
  ui/package.json
  ui/src/admin/components/chronograf/OrganizationsTable.js
  ui/src/admin/components/chronograf/OrganizationsTableRow.tsx
  ui/src/admin/components/chronograf/UsersTable.js
  ui/src/admin/components/chronograf/UsersTableRow.js
  ui/src/admin/components/chronograf/UsersTableRow.tsx
  ui/src/admin/containers/chronograf/UsersPage.js
  ui/src/shared/components/ConfirmButton.tsx
  ui/yarn.lock
Labels: bugfix

#3204 Notify when User adds, deletes, or clones a cell
  CHANGELOG.md
  ui/src/dashboards/actions/index.js
  ui/src/shared/copy/notifications.js
Labels: User Experience

#3202 Improve box packing for New and Cloned cells
  ui/src/dashboards/utils/cellGetters.js
Labels: polish

#3259 Polish Some Small Details
  ui/src/style/components/resizer.scss
  ui/src/style/pages/dashboards.scss
Labels: polish

#3267 Fix TICKscript Editor Overflow
  ui/src/style/components/code-mirror-theme.scss
Labels: bugfix

#3266 Show New Cell's Name in Notification
  ui/src/dashboards/actions/index.js
  ui/src/dashboards/constants/index.js
  ui/src/dashboards/containers/DashboardsPage.js
  ui/src/dashboards/utils/cellGetters.js
  ui/src/shared/copy/notifications.js
  ui/test/dashboards/reducers/cellEditorOverlay.test.js
Labels: bugfix

#3276 Fix Jittery Template Variable Dropdowns
  ui/src/dashboards/constants/templateControlBar.js
Labels: bugfix

#3279 Improve Threshold UX
  CHANGELOG.md
  ui/src/shared/constants/colorOperations.js
Labels: User Experience, bugfix

#3283 Generic Page Tabs
  ui/src/admin/components/AdminTabs.js
  ui/src/admin/components/DatabaseRow.js
  ui/src/admin/components/DatabaseTableHeader.js
  ui/src/admin/components/RoleEditingRow.js
  ui/src/admin/components/UserEditName.js
  ui/src/admin/components/UserNewPassword.js
  ui/src/admin/containers/AdminInfluxDBPage.js
  ui/src/dashboards/components/template_variables/RowValues.js
  ui/src/index.tsx
  ui/src/shared/components/SubSections.tsx
  ui/src/shared/components/SubSectionsTab.tsx
  ui/src/side_nav/components/NavItems.tsx
  ui/src/side_nav/containers/SideNav.tsx
  ui/src/style/chronograf.scss
  ui/src/style/layout/page-subsections.scss
  ui/src/style/pages/admin.scss
  ui/src/types/shared.ts
  ui/test/shared/components/SubSections.test.tsx
Labels: enhancement

#3313 Polish Chronograf Admin Tabs
  ui/src/admin/components/chronograf/AdminTabs.js
  ui/src/admin/containers/chronograf/AdminChronografPage.js
  ui/src/index.tsx
  ui/src/side_nav/containers/SideNav.tsx
Labels: polish
