Repository influxdata/chronograf, pull requests merged in 2018-03, with the labels that each got.

#2886 Prevent Threshold Jumping
  CHANGELOG.md
  ui/src/dashboards/components/GaugeOptions.js
  ui/src/dashboards/components/SingleStatOptions.js
  ui/src/dashboards/components/Threshold.js
  ui/src/dashboards/constants/gaugeColors.js
Labels: polish

#2927 First Pass at Table Graph Styles
  ui/src/dashboards/components/AxesOptions.js
  ui/src/dashboards/components/GaugeOptions.js
  ui/src/dashboards/components/GraphOptionsCustomizableColumn.js
  ui/src/dashboards/components/GraphOptionsCustomizeColumns.js
  ui/src/dashboards/components/GraphOptionsSortBy.js
  ui/src/dashboards/components/GraphOptionsTextWrapping.js
  ui/src/dashboards/components/GraphOptionsThresholdColoring.js
  ui/src/dashboards/components/GraphOptionsThresholds.js
  ui/src/dashboards/components/GraphOptionsTimeAxis.js
  ui/src/dashboards/components/GraphOptionsTimeFormat.js
  ui/src/dashboards/components/SingleStatOptions.js
  ui/src/dashboards/components/TableOptions.js
  ui/src/dashboards/graphics/graph.js
  ui/src/shared/components/InputClickToEdit.js
  ui/src/shared/components/TableGraph.js
  ui/src/style/chronograf.scss
  ui/src/style/components/ceo-display-options.scss
  ui/src/style/components/input-click-to-edit.scss
  ui/src/style/components/table-graph.scss
  ui/src/style/theme/_form-elements.scss
Labels: design

#2910 Redesign & Refactor Notifications
  CHANGELOG.md
  ui/package.json
  ui/src/App.js
  ui/src/CheckSources.js
  ui/src/admin/actions/chronograf.js
  ui/src/admin/actions/influxdb.js
  ui/src/admin/components/DatabaseManager.js
  ui/src/admin/components/DatabaseRow.js
  ui/src/admin/components/DatabaseTable.js
  ui/src/admin/components/DatabaseTableHeader.js
  ui/src/admin/components/chronograf/AllUsersTable.js
  ui/src/admin/components/chronograf/AllUsersTableRowNew.js
  ui/src/admin/components/chronograf/UsersTable.js
  ui/src/admin/components/chronograf/UsersTableRowNew.js
  ui/src/admin/containers/AdminInfluxDBPage.js
  ui/src/admin/containers/DatabaseManagerPage.js
  ui/src/admin/containers/ProvidersPage.js
  ui/src/admin/containers/QueriesPage.js
  ui/src/admin/containers/chronograf/AllUsersPage.js
  ui/src/admin/containers/chronograf/UsersPage.js
  ui/src/dashboards/actions/index.js
  ui/src/dashboards/components/template_variables/Row.js
  ui/src/dashboards/containers/DashboardPage.js
  ui/src/data_explorer/actions/view/write.js
  ui/src/hosts/containers/HostsPage.js
  ui/src/kapacitor/actions/view/index.js
  ui/src/kapacitor/components/AlertOutputs.tsx
  ui/src/kapacitor/components/AlertTabs.js
  ui/src/kapacitor/components/DataSection.js
  ui/src/kapacitor/components/KapacitorForm.tsx
  ui/src/kapacitor/components/KapacitorRule.js
  ui/src/kapacitor/containers/KapacitorPage.tsx
  ui/src/kapacitor/containers/KapacitorRulePage.js
  ui/src/kapacitor/containers/KapacitorRulesPage.js
  ui/src/kapacitor/containers/KapacitorTasksPage.js
  ui/src/kapacitor/containers/TickscriptPage.js
  ui/src/localStorage.js
  ui/src/shared/actions/auth.js
  ui/src/shared/actions/notifications.js
  ui/src/shared/actions/sources.js
  ui/src/shared/apis/index.js
  ui/src/shared/components/Notification.js
  ui/src/shared/components/Notifications.js
  ui/src/shared/constants/index.js
  ui/src/shared/copy/notifications.js
  ui/src/shared/dispatchers/index.js
  ui/src/shared/middleware/errors.js
  ui/src/shared/reducers/index.js
  ui/src/shared/reducers/notifications.js
  ui/src/sources/containers/ManageSources.js
  ui/src/sources/containers/SourcePage.js
  ui/src/style/chronograf.scss
  ui/src/style/layout/flash-messages.scss
  ui/src/style/theme/_alerts.scss
  ui/src/style/theme/_notifications.scss
  ui/src/style/theme/chronograf-theme.scss
  ui/test/kapacitor/containers/KapacitorPage.test.tsx
  ui/test/shared/reducers/notifications.test.js
  ui/yarn.lock
Labels: User Experience, design, polish

#3012 Misc. Polish
  ui/src/admin/components/chronograf/AllUsersTableRow.js
  ui/src/admin/components/chronograf/ProvidersTable.js
  ui/src/admin/components/chronograf/ProvidersTableRow.js
  ui/src/admin/components/chronograf/ProvidersTableRowNew.tsx
  ui/src/shared/components/Dropdown.js
  ui/src/shared/components/DropdownHead.js
  ui/src/shared/components/DropdownInput.js
  ui/src/shared/components/Tags.js
  ui/src/style/components/input-tag-list.scss
  ui/src/style/theme/_tables.scss
  ui/src/style/unsorted.scss
Labels: bugfix, polish

#3020 Update Icon Font
  ui/src/style/fonts/icomoon.eot
  ui/src/style/fonts/icomoon.svg
  ui/src/style/fonts/icomoon.ttf
  ui/src/style/fonts/icomoon.woff
  ui/src/style/fonts/icomoon.woff2
  ui/src/style/fonts/icon-font.scss
Labels: design

#3024 Polish Table Styles
  ui/src/dashboards/components/GraphOptionsTimeFormat.tsx
  ui/src/shared/components/TableGraph.js
  ui/src/shared/components/ThresholdsList.js
  ui/src/style/components/table-graph.scss
Labels: design, polish

#3036 More Table Polish
  ui/src/shared/components/SingleStat.js
  ui/src/shared/components/TableGraph.js
  ui/src/shared/constants/colorOperations.js
  ui/src/shared/constants/tableGraph.js
Labels: design

#3034 Style Table Sorting
  ui/src/shared/components/TableGraph.js
  ui/src/style/components/table-graph.scss
Labels: design

#3040 Polish Customizable Fields UI
  ui/src/dashboards/components/GraphOptionsCustomizableField.tsx
  ui/src/dashboards/components/GraphOptionsCustomizeFields.tsx
  ui/src/style/chronograf.scss
  ui/src/style/components/ceo-display-options.scss
  ui/src/style/components/customize-fields.scss
  ui/test/dashboards/components/GraphOptionsCustomizeFields.test.tsx
Labels: design, polish

#3041 Change "Fix First Column" to "Lock First Column"
  ui/src/dashboards/components/GraphOptionsFixFirstColumn.tsx
Labels: polish

#3042 Make Notification Constants into Functions
  ui/src/CheckSources.js
  ui/src/admin/actions/chronograf.js
  ui/src/admin/actions/influxdb.js
  ui/src/admin/components/DatabaseRow.js
  ui/src/admin/components/DatabaseTableHeader.js
  ui/src/admin/components/chronograf/AllUsersTable.js
  ui/src/admin/components/chronograf/AllUsersTableRowNew.js
  ui/src/admin/components/chronograf/UsersTableRowNew.js
  ui/src/admin/containers/AdminInfluxDBPage.js
  ui/src/admin/containers/DatabaseManagerPage.js
  ui/src/admin/containers/QueriesPage.js
  ui/src/dashboards/actions/index.js
  ui/src/dashboards/components/template_variables/Row.js
  ui/src/dashboards/containers/DashboardPage.js
  ui/src/data_explorer/actions/view/write.js
  ui/src/hosts/containers/HostsPage.js
  ui/src/index.js
  ui/src/kapacitor/actions/view/index.js
  ui/src/kapacitor/components/AlertTabs.js
  ui/src/kapacitor/components/KapacitorRule.js
  ui/src/kapacitor/containers/KapacitorPage.tsx
  ui/src/kapacitor/containers/KapacitorRulePage.js
  ui/src/kapacitor/containers/TickscriptPage.js
  ui/src/localStorage.js
  ui/src/shared/actions/auth.js
  ui/src/shared/actions/sources.js
  ui/src/shared/components/LayoutCell.js
  ui/src/shared/copy/notifications.js
  ui/src/shared/dispatchers/index.js
  ui/src/shared/middleware/errors.js
  ui/src/sources/containers/ManageSources.js
  ui/src/sources/containers/SourcePage.js
  ui/src/status/actions/index.js
Labels: chore

#3048 Prevent Multi-Select Dropdown in InfluxDB Admin Users and Roles tabs from losing selection state
  CHANGELOG.md
  ui/src/admin/components/RoleRow.js
  ui/src/admin/components/UserRow.js
  ui/src/shared/components/MultiSelectDropdown.js
Labels: bugfix

#3053 Improve Table Graph Column Width Calculations
  ui/src/shared/components/TableGraph.js
  ui/src/shared/constants/tableGraph.js
Labels: polish

#3085 Change annotation date format to: YYYY/MM/DD
  ui/src/shared/components/AnnotationTooltip.js
Labels: ship stopper

#3082 Support custom time range in annotations api wrapper
  CHANGELOG.md
  ui/src/dashboards/containers/DashboardPage.js
  ui/src/shared/actions/annotations.js
  ui/src/shared/apis/annotation.js
Labels: ship stopper

#3087 Improve Annotation Edit Mode
  CHANGELOG.md
  ui/src/dashboards/containers/DashboardPage.js
  ui/src/shared/components/LayoutCellMenu.js
Labels: ship stopper

#3073 Fix Delete Button in All Users Admin Table
  CHANGELOG.md
  ui/src/admin/components/chronograf/AllUsersTableRow.js
  ui/src/admin/components/chronograf/UsersTableRow.js
Labels: bugfix

#2656 Update Swagger for most multiorganization & multiuser changes
  server/swagger.json
Labels: in progress

#3096 Standardize Confirmation Buttons
  CHANGELOG.md
  ui/src/admin/components/ChangePassRow.js
  ui/src/admin/components/DatabaseRow.js
  ui/src/admin/components/DatabaseTableHeader.js
  ui/src/admin/components/QueryRow.js
  ui/src/admin/components/RoleRow.js
  ui/src/admin/components/UserRow.js
  ui/src/admin/components/chronograf/OrganizationsTableRow.js
  ui/src/admin/components/chronograf/OrganizationsTableRowNew.js
  ui/src/admin/components/chronograf/ProvidersTableRow.js
  ui/src/admin/components/chronograf/ProvidersTableRowNew.tsx
  ui/src/admin/components/chronograf/UsersTableRow.js
  ui/src/admin/constants/tableSizing.js
  ui/src/dashboards/components/DashboardsTable.js
  ui/src/dashboards/components/OverlayControls.js
  ui/src/dashboards/components/template_variables/Row.js
  ui/src/dashboards/components/template_variables/RowButtons.js
  ui/src/shared/components/ConfirmOrCancel.tsx
  ui/src/shared/components/DeleteConfirmButtons.js
  ui/src/shared/components/DeleteConfirmTableCell.js
  ui/src/shared/components/YesNoButtons.js
  ui/src/sources/components/InfluxTable.js
  ui/src/style/chronograf.scss
  ui/src/style/components/confirm-buttons.scss
  ui/src/style/components/confirm-or-cancel.scss
  ui/src/style/components/fancy-table.scss
  ui/src/style/components/organizations-table.scss
  ui/src/style/components/template-variables-manager.scss
  ui/src/style/pages/manage-providers.scss
  ui/src/style/pages/overlay-technology.scss
  ui/src/style/theme/_tables.scss
  ui/src/style/unsorted.scss
  ui/test/shared/components/ConfirmOrCancel.test.tsx
  ui/test/shared/components/ProvidersTableRowNew.test.tsx
Labels: User Experience

#3088 Improve Add New Cell UX
  CHANGELOG.md
  ui/src/dashboards/actions/index.js
  ui/src/dashboards/constants/index.js
Labels: User Experience, polish

#3103 Add Ability to Clone Dashboards
  CHANGELOG.md
  ui/src/dashboards/components/DashboardsPageContents.js
  ui/src/dashboards/components/DashboardsTable.js
  ui/src/dashboards/containers/DashboardsPage.js
  ui/test/dashboards/reducers/ui.test.js
Labels: feature request
